#!/usr/bin/env bash
# Start nftconf daemon inside the gw container.
set -euo pipefail

ROOT=/opt/nftconf
DEMO="$ROOT/demo"
PIDFILE=/run/nftconf.pid
RUNTIME_CONF=/run/nftconf/nftconf.conf

export PYTHONPATH="$ROOT"
export PATH="$ROOT:$PATH"

mkdir -p /run/nftconf
# Prefer compose sysctls; fall back if the runtime allows it.
sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1 || true

iface_for_addr() {
  local addr=$1
  ip -4 -o addr show | awk -v a="$addr" '$0 ~ ("inet " a "/") { print $2; exit }'
}

EXT_IF=$(iface_for_addr 10.66.10.2 || true)
INT_IF=$(iface_for_addr 10.66.20.2 || true)
MGMT_IF=$(iface_for_addr 10.66.30.2 || true)

echo "nftconf demo gw: ext=${EXT_IF:-?} int=${INT_IF:-?} mgmt=${MGMT_IF:-?}"

# Resolve iface names by address so multi-NIC context stays correct.
{
  echo "# generated by entrypoint.sh — do not edit"
  echo
  echo "table demo"
  echo "priority filter"
  echo
  echo "# --- external (NAT + shield) ---"
  if [[ -n "${EXT_IF:-}" ]]; then
    echo "interface $EXT_IF"
  fi
  echo "address 10.66.10.2"
  echo "dest address 10.66.20.10"
  echo
  echo "include $DEMO/conf.d/nat.conf"
  echo "include $DEMO/conf.d/whitelist.conf"
  echo
  echo "# --- management (address/NIC scope) ---"
  if [[ -n "${MGMT_IF:-}" ]]; then
    echo "interface $MGMT_IF"
  fi
  echo "address 10.66.30.2"
  echo
  echo "include $DEMO/conf.d/mgmt.conf"
} >"$RUNTIME_CONF"

listen_port() {
  local port=$1
  # openbsd-netcat: nc -l PORT
  while true; do
    printf 'HTTP/1.0 200 OK\r\nContent-Length: 3\r\n\r\nok\n' | nc -l -q 0 "$port" || true
  done
}

for port in 2222 9090 9100; do
  listen_port "$port" &
done

if [[ -f "$PIDFILE" ]]; then
  old=$(tr -d ' \n' <"$PIDFILE" || true)
  if [[ -n "$old" ]] && kill -0 "$old" 2>/dev/null; then
    echo "nftconf already running (pid $old); refusing second instance" >&2
    exit 1
  fi
  rm -f "$PIDFILE"
fi

stop_daemon() {
  if [[ -f "$PIDFILE" ]]; then
    python3 -m nftconf_app stop --pid "$PIDFILE" 2>/dev/null || true
  fi
}
trap 'stop_daemon; exit 0' SIGTERM SIGINT

echo "starting: nftconf daemon $RUNTIME_CONF --pid $PIDFILE"
python3 -m nftconf_app daemon -v "$RUNTIME_CONF" --pid "$PIDFILE" &
child=$!
wait "$child"
