"""Render consolidated nftables config for `convert`."""

from __future__ import annotations

import re
from typing import Iterable

from nftconf_app import VERSION
from nftconf_app.model import Config, SemNat, port_atoms


def _nft_ident(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not s or s[0].isdigit():
        s = "t_" + s
    return s


def _port_set_literal(ports: Iterable[str]) -> str:
    """Build nft set body: { 80, 443, 5000-5010 }."""
    items = sorted(set(ports), key=lambda p: (int(p.split("-")[0]), p))
    return "{ " + ", ".join(items) + " }"


def _render_nftables(cfg: Config) -> str:
    """Render consolidated nftables config (defines + sets + tables)."""
    nats = list(cfg.sem_nat)
    wls = list(cfg.sem_wl)

    ext_nic = next((n.interface for n in nats if n.interface), None) or next(
        (w.interface for w in wls if w.interface), None
    )
    ext_ips = list(
        dict.fromkeys(
            [a for n in nats for a in n.daddrs] + [a for w in wls for a in w.daddrs]
        )
    )
    vip_ips = list(dict.fromkeys(n.to_addr for n in nats))
    family = (nats[0].family if nats else None) or (wls[0].family if wls else "ip")
    table_base = (nats[0].table if nats else None) or (
        wls[0].table if wls else "nftconf"
    )
    t_filter = _nft_ident(f"{table_base}_filter")
    t_nat = _nft_ident(f"{table_base}_nat")

    onetoone: dict[tuple, list[str]] = {}
    onetoone_rep: dict[tuple, SemNat] = {}
    irregular: list[SemNat] = []
    for n in nats:
        if n.to_ports != n.dports:
            irregular.append(n)
            continue
        key = (n.op, n.proto, n.daddrs, n.to_addr, n.interface, n.table, n.family)
        onetoone.setdefault(key, []).extend(port_atoms(n.dports))
        onetoone_rep[key] = n

    app_ports = list(dict.fromkeys(p for ports in onetoone.values() for p in ports))
    wl_ports = list(dict.fromkeys(a for w in wls for a in port_atoms(w.dports)))

    lines: list[str] = [
        f"# Generated by nftconf {VERSION} from {cfg.path}",
        "# Regenerate: nftconf convert <file>",
        "",
        "# -------------------------------------------------------------",
        "# 1. Variables",
        "# -------------------------------------------------------------",
    ]
    if ext_nic:
        lines.append(f'define ext_nic = "{ext_nic}"')
    if len(ext_ips) == 1:
        lines.append(f"define ext_ip  = {ext_ips[0]}")
    elif ext_ips:
        lines.append(f"define ext_ips = {{ {', '.join(ext_ips)} }}")
    if len(vip_ips) == 1:
        lines.append(f"define os_vip  = {vip_ips[0]}")
    elif vip_ips:
        for i, v in enumerate(vip_ips):
            lines.append(f"define os_vip_{i} = {v}")
    if app_ports:
        lines.append(f"define app_ports = {_port_set_literal(app_ports)}")
    if wl_ports:
        lines.append(f"define whitelist_ports = {_port_set_literal(wl_ports)}")
    lines.append("")

    def daddr_expr(addrs: tuple[str, ...]) -> str:
        if not addrs:
            return ""
        if len(addrs) == 1 and ext_ips == list(addrs):
            return "ip daddr $ext_ip "
        if len(addrs) == 1:
            return f"ip daddr {addrs[0]} "
        return f"ip daddr {{ {', '.join(addrs)} }} "

    def vip_expr(addr: str) -> str:
        if len(vip_ips) == 1 and addr == vip_ips[0]:
            return "$os_vip"
        return addr

    def ports_expr(ports: list[str]) -> str:
        ports_u = list(dict.fromkeys(ports))
        if set(ports_u) == set(app_ports) and len(app_ports) > 1:
            return "$app_ports"
        if len(ports_u) > 1:
            return _port_set_literal(ports_u)
        return ports_u[0]

    iif = "iifname $ext_nic " if ext_nic else ""

    # Filter/whitelist: only explicit whitelist/accept (NAT ports stay in nat hooks)
    if wl_ports or cfg.shield_wanted:
        lines += [
            "# -------------------------------------------------------------",
            "# 2. Filter / whitelist",
            "# -------------------------------------------------------------",
            f"table {family} {t_filter} {{",
            "    chain input {",
            "        type filter hook input priority filter; policy accept;",
            "",
        ]
        daddr = daddr_expr(tuple(ext_ips)) if ext_ips else ""
        if cfg.shield_wanted:
            lines.append("        ct state established,related accept")
            lines.append("        ip protocol icmp accept")
            if wl_ports:
                proto = wls[0].proto if wls else "tcp"
                lines.append(
                    f"        {iif}{daddr}{proto} dport $whitelist_ports accept"
                )
            lines.append(f"        {iif}{daddr}drop".rstrip())
        else:
            if wl_ports:
                proto = wls[0].proto if wls else "tcp"
                lines.append(
                    f"        {iif}{daddr}{proto} dport $whitelist_ports accept"
                )
        lines += ["    }", "}", ""]

    if nats:
        lines += [
            "# -------------------------------------------------------------",
            "# 3. NAT (prerouting / output / postrouting)",
            "# -------------------------------------------------------------",
            f"table {family} {t_nat} {{",
            "    chain prerouting {",
            "        type nat hook prerouting priority dstnat; policy accept;",
        ]
        for key, ports in onetoone.items():
            rep = onetoone_rep[key]
            lines.append(
                f"        {iif}{daddr_expr(rep.daddrs)}{rep.proto} dport "
                f"{ports_expr(ports)} dnat to {vip_expr(rep.to_addr)}"
            )
        for n in irregular:
            lines.append(
                f"        {iif}{daddr_expr(n.daddrs)}{n.proto} dport {n.dports} "
                f"dnat to {n.to_addr}:{n.to_ports}"
            )
        lines += [
            "    }",
            "",
            "    chain output {",
            "        type nat hook output priority -100; policy accept;",
        ]
        for key, ports in onetoone.items():
            rep = onetoone_rep[key]
            lines.append(
                f"        {daddr_expr(rep.daddrs)}{rep.proto} dport "
                f"{ports_expr(ports)} dnat to {vip_expr(rep.to_addr)}"
            )
        for n in irregular:
            lines.append(
                f"        {daddr_expr(n.daddrs)}{n.proto} dport {n.dports} "
                f"dnat to {n.to_addr}:{n.to_ports}"
            )
        lines += [
            "    }",
            "",
            "    chain postrouting {",
            "        type nat hook postrouting priority srcnat; policy accept;",
        ]
        for key, ports in onetoone.items():
            rep = onetoone_rep[key]
            if rep.op != "nat" or len(rep.daddrs) != 1:
                continue
            snat_to = (
                "$ext_ip"
                if len(ext_ips) == 1 and rep.daddrs[0] == ext_ips[0]
                else rep.daddrs[0]
            )
            lines.append(
                f"        ip daddr {vip_expr(rep.to_addr)} {rep.proto} dport "
                f"{ports_expr(ports)} snat to {snat_to}"
            )
        for n in irregular:
            if n.op != "nat" or len(n.daddrs) != 1:
                continue
            lines.append(
                f"        ip daddr {n.to_addr} {n.proto} dport {n.to_ports} "
                f"snat to {n.daddrs[0]}"
            )
        lines += ["    }", "}", ""]

    if len(lines) <= 8:
        lines.append("# (no nat/whitelist rules)")
        lines.append("")

    return "\n".join(lines) + "\n"
