= nftconf(1)
Lenik <nftconf@bodz.net>
v{project-version}, {project-year}
:doctype: manpage
:manmanual: Uzantaj komandoj
:mansource: nftconf
:man-linkstyle: blue R <>
:nofooter:

== Nomo

nftconf - deklara nftables-agordo kun viva kunigo

== Sintakso

*nftconf* [_MALLOKA_]... _CMD_ [_OPCIO_]... [_FILE_]...

== Priskribo

*nftconf* legas mallongan deklaran agordon kaj kunigas ĝin kun la viva
*nftables*(8)-reguloj. Ĉiu logika regulo havas posedan komenton, tiel ke
*load*, *unload* kaj *daemon* ŝanĝas nur regulojn de tiu dosiero.

NAT funkcias ĉe prerouting/output/postrouting kaj *ne* malfermas *INPUT*.
Gastigantaj pordoj bezonas eksplicitan *allow incoming* (aŭ *whitelist*,
laŭvole *shield on*).

== Komandoj

*load* _FILE_::
  Kunigas _FILE_ kun la vivaj reguloj. Implicite unu frazo fariĝas unu
  nft-regulo. *-c, --compact* pakas kongruajn allow/deny en nft-arojn
  (antaŭa konduto).

*unload* _FILE_::
  Forigas vivan regulon nur kiam la tuta frazo kongruas. *-f, --force*
  disigas restantan kompaktigitan regulon kaj forigas kiom eble da atomoj
  (fonto mallongigita aŭ ŝanĝita).

*status* _FILE_::
  Montras diferencon inter dezirataj kaj vivaj reguloj.

*check* _FILE_::
  Analizas kaj presas solvitajn nft-regulojn (sen apliki).

*show* _FILE_::
  Presas ĉiun frazon kun 8-larĝa stata kolumno: *on* (tute viva),
  *N/M* (parta), *---* (ne ŝargita), *xxx* (sintaksa eraro).

*daemon* _FILE_::
  Observas _FILE_ (kaj include) per inotify; reŝargas ĉe ŝanĝo.
  Implicita pidfile */run/nftconf.pid*; dua instanco estas rifuzata.

*stop*::
  Haltigas la demonon per la pidfile (*--pid*).

*convert* _FILE_...::
  Skribas kunigitajn *nftables.d/\*.nft* (difinoj kaj pordaroj).

*help*::
  Montras uzon.

== Mallokaj opcioj

*-v, --verbose*::
  Sencimiga protokolo (ripetebla).

*-q, --quiet*::
  Nur eraroj.

*-h, --help*::
  Montri helpon.

*--version*::
  Presi version kaj eliri.

== Konfliktopolitiko

Validas por *load*, *daemon* kaj *convert*:

(implicite)::
  Ĉesigi se ekzistantaj nft-agordoj konfliktas.

*-f, --force*::
  Anstataŭigi konfliktajn vivajn regulojn (*load*).

*-n, --no-clobber*::
  Preterlasi konfliktajn ŝanĝojn.

*--dry-run*::
  Montri agojn sen apliki.

*load -c/--compact*::
  Paki kongruajn frazojn en nft-arojn.

*unload -f/--force*::
  Disigi restantajn kompaktigitajn regulojn kaj forigi kongruajn atomojn.

== Agordolingvo

Unu direktivo po linio. Malplenaj linioj estas ignorataj. *#* komencas
komenton (krom en citiloj). Komento sur la sama linio kiel NAT- aŭ
filtrila frazo estas kopiata en la nft-regulon post la poseda etikedo.
La unua ĵetono estas la direktivo; nomoj kaj ŝlosilvortoj ne distingas
usklecon. Kunteksto daŭras ĝis la sekva kunteksta direktivo. Ne estas
bloka sintakso.

=== Kunteksto

*table* _NOMO_ [_FAMILIO_]::
  Cela tabelo (implicite *nftconf*). Familio *ip* (implicite), *ip6*,
  *inet*, *arp*, *bridge*, *netdev*.

*interface* _IFACE_...::
  Kongruigi *iifname*; ankaŭ solvi IPv4 de tiuj NIC ĝis *address*.
  Unu regulo po interfaco.

*address* _ADDR_...::
  Celdirekta kongruo (*ip daddr*). Anstataŭas interfacan solvon.

*dest address* / *dest interface*::
  Implicita interna/VIP-flanko por `nat … to PORT`. *destination* estas
  kromnomo de *dest*.

*priority* _NOMO_|_NOMBRO_::
  Prioritato de INPUT-hoko. NAT-hokoj ignoras tion.

*shield* *on*|*off*::
  Defaŭlte forĵetanta INPUT-permeslisto por la nuna interfaco/adresa
  amplekso. *on* sola ne malfermas aplikaĵajn pordojn.

*include* _GLOB_::
  Inkludi dosierojn (relative al la inkluda dosiero); heredas kopion de
  la nuna kunteksto.

=== Pordoj (tcp / udp / sctp / dccp)

Post porda protokolo: pordo, ferma intervalo, aŭ listo (spacetoj kaj/aŭ
komoj). Unu ero estas skalaro/intervalo; du aŭ pli fariĝas anonima
nftables-aro.

----
allow incoming tcp 22
allow incoming tcp 8000-8080
allow incoming tcp 80 443 1080 8000-8080
deny incoming tcp 33
allow outgoing ip 10.0.0.0/8 tcp 443
nat tcp 80 443 8000-8080 to 10.0.0.50
----

Pordoj 0–65535; *HIGH* ≥ *LOW*. Laŭvola prefikso *ADDR:PORT* (aŭ
*[IPv6]:PORT*). Alie *address* / *interface* liveras *ip daddr*.

Listoj validas ĉe *allow* / *deny* / *whitelist* / *blacklist* kaj ĉe
*nat* / *dnat* / *snat* / *masquerade* / *redirect* (antaŭ *to*), ne ĉe
*icmp* / *ct*.

=== NAT kaj filtrilo

*nat* / *dnat* / *snat* _PROTO_ _PORT_... *to* _DEST_, *masquerade*,
*redirect*. NAT ne malfermas *INPUT*.

*allow incoming* / *deny incoming* (kromnomoj *whitelist* / *blacklist*)
aplikiĝas al INPUT. *allow outgoing ip CIDR* [*PROTO* [_PORT_...]]
aplikiĝas al OUTPUT; preterlasi proton/pordojn kongruas la tutan trafikon
al tiu CIDR.

*Unuopa pordo* kongruas antaŭ *intervalo*; ĉe sama specifaĵo *allow*
venkas *deny*.

Kun *shield on* enira politiko eniras la ŝildan ĉenon.

Ĉio post *reject … with* iras al nftables (*tcp reset*, …).

Vidu *guide.md* kaj `info nftconf`.

== Dosieroj

*/run/nftconf.pid*::
  Implicita pidfile de la demono.

*nftables.d/\*.nft*::
  Implicita eliga dosierujo de *convert*.

== Elirstato

*0*:: Sukceso.

*1*:: Agorda/konflikta/rultempa eraro.

*2*:: Uzeraro.

== Vidu ankaŭ

*nft*(8), *nftables*(8), *guide.md*, Texinfo-manlibro (*info nftconf*),
kaj Docker-laboratorio *demo/README.md*.

== Cimoj

Raporti al: <{project-email}>

== Aŭtoro

Verkita de {project-author} <{project-email}>.

== Kopirajto

Copyright \(C) {project-year} {project-author}.
Permesilo AGPL-3.0-or-later.
Ĉi tiu projekto kontraŭas AI-ekspluatadon kaj AI-hegemonion, kaj rifuzas
senpensajn MIT-stilajn kaj politike naivajn BSD-stilajn permesilojn.
